### ISSUE TITLE
Problem with "from dictvariable get" block intellisense

### ISSUE THREAD

**Issue by kbridson** [aolney/jupyterlab-blockly-python-extension#11]
On the "from dictvariable get” block, the intellisense seems to automatically populate the first possible choice. However, when you hit Blocks to Code with that selected, it seems to think nothing was selected which can be pretty misleading. To fix, you have to open the dropdown and select the option that is already selected.

<img width="1201" alt="Screenshot 2024-05-30 at 3 42 17 PM" src="https://github.com/aolney/jupyterlab-blockly-python-extension/assets/21212136/cb984c30-6b35-425c-9fb8-09a5950a7895">

It either needs to not visually indicate that the first choice is selected when it’s not really selected or it needs to actually select the first choice.

**Comment by aolney** [comment]
Fixed with https://github.com/aolney/jupyterlab-blockly-python-extension/commit/70c8b3fa205b0c96bff0b8c121cb02908fcc6b0e

This problem affected all intelliblocks, not just the get block. The problem was that the default option was being set, but in between updating events, the original value was saved in a closure, so the default option was having no effect. Now the closure checks the updated value.

If this change introduces any bugs we can roll back.

BTW it can be a bit dicey to use `get` on a dataframe if you add columns dynamically (e.g. after reading a dataframe from file). This is because the intellisense caching does not count children but rather checks if there are **any** children. This means that once a variable has children, caching will not update. I plan on changing this in the next version.
